package com.landasoft.xysh.mapper;

import com.landasoft.xysh.pojo.TScreenChart;
import com.landasoft.xysh.pojo.TScreenChartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TScreenChartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    int countByExample(TScreenChartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    int deleteByExample(TScreenChartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    int deleteByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    int insert(TScreenChart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    int insertSelective(TScreenChart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    List<TScreenChart> selectByExample(TScreenChartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    TScreenChart selectByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") TScreenChart record, @Param("example") TScreenChartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    int updateByExample(@Param("record") TScreenChart record, @Param("example") TScreenChartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    int updateByPrimaryKeySelective(TScreenChart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    int updateByPrimaryKey(TScreenChart record);
}