package com.landasoft.xysh.mapper;

import com.landasoft.xysh.pojo.TScreenHz;
import com.landasoft.xysh.pojo.TScreenHzExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TScreenHzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_hz
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    int countByExample(TScreenHzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_hz
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    int deleteByExample(TScreenHzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_hz
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    int deleteByPrimaryKey(String sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_hz
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    int insert(TScreenHz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_hz
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    int insertSelective(TScreenHz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_hz
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    List<TScreenHz> selectByExample(TScreenHzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_hz
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    TScreenHz selectByPrimaryKey(String sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_hz
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") TScreenHz record, @Param("example") TScreenHzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_hz
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    int updateByExample(@Param("record") TScreenHz record, @Param("example") TScreenHzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_hz
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    int updateByPrimaryKeySelective(TScreenHz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_hz
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    int updateByPrimaryKey(TScreenHz record);
}