package com.landasoft.xysh.mapper;

import com.landasoft.xysh.pojo.TScreenList;
import com.landasoft.xysh.pojo.TScreenListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TScreenListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    int countByExample(TScreenListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    int deleteByExample(TScreenListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    int deleteByPrimaryKey(String lId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    int insert(TScreenList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    int insertSelective(TScreenList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    List<TScreenList> selectByExample(TScreenListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    TScreenList selectByPrimaryKey(String lId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") TScreenList record, @Param("example") TScreenListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    int updateByExample(@Param("record") TScreenList record, @Param("example") TScreenListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    int updateByPrimaryKeySelective(TScreenList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    int updateByPrimaryKey(TScreenList record);
}