package com.landasoft.xysh.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TScreenChartExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public TScreenChartExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCIdIsNull() {
            addCriterion("C_ID is null");
            return (Criteria) this;
        }

        public Criteria andCIdIsNotNull() {
            addCriterion("C_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCIdEqualTo(String value) {
            addCriterion("C_ID =", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotEqualTo(String value) {
            addCriterion("C_ID <>", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdGreaterThan(String value) {
            addCriterion("C_ID >", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdGreaterThanOrEqualTo(String value) {
            addCriterion("C_ID >=", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLessThan(String value) {
            addCriterion("C_ID <", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLessThanOrEqualTo(String value) {
            addCriterion("C_ID <=", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLike(String value) {
            addCriterion("C_ID like", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotLike(String value) {
            addCriterion("C_ID not like", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdIn(List<String> values) {
            addCriterion("C_ID in", values, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotIn(List<String> values) {
            addCriterion("C_ID not in", values, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdBetween(String value1, String value2) {
            addCriterion("C_ID between", value1, value2, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotBetween(String value1, String value2) {
            addCriterion("C_ID not between", value1, value2, "cId");
            return (Criteria) this;
        }

        public Criteria andCScreenIdIsNull() {
            addCriterion("C_SCREEN_ID is null");
            return (Criteria) this;
        }

        public Criteria andCScreenIdIsNotNull() {
            addCriterion("C_SCREEN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCScreenIdEqualTo(String value) {
            addCriterion("C_SCREEN_ID =", value, "cScreenId");
            return (Criteria) this;
        }

        public Criteria andCScreenIdNotEqualTo(String value) {
            addCriterion("C_SCREEN_ID <>", value, "cScreenId");
            return (Criteria) this;
        }

        public Criteria andCScreenIdGreaterThan(String value) {
            addCriterion("C_SCREEN_ID >", value, "cScreenId");
            return (Criteria) this;
        }

        public Criteria andCScreenIdGreaterThanOrEqualTo(String value) {
            addCriterion("C_SCREEN_ID >=", value, "cScreenId");
            return (Criteria) this;
        }

        public Criteria andCScreenIdLessThan(String value) {
            addCriterion("C_SCREEN_ID <", value, "cScreenId");
            return (Criteria) this;
        }

        public Criteria andCScreenIdLessThanOrEqualTo(String value) {
            addCriterion("C_SCREEN_ID <=", value, "cScreenId");
            return (Criteria) this;
        }

        public Criteria andCScreenIdLike(String value) {
            addCriterion("C_SCREEN_ID like", value, "cScreenId");
            return (Criteria) this;
        }

        public Criteria andCScreenIdNotLike(String value) {
            addCriterion("C_SCREEN_ID not like", value, "cScreenId");
            return (Criteria) this;
        }

        public Criteria andCScreenIdIn(List<String> values) {
            addCriterion("C_SCREEN_ID in", values, "cScreenId");
            return (Criteria) this;
        }

        public Criteria andCScreenIdNotIn(List<String> values) {
            addCriterion("C_SCREEN_ID not in", values, "cScreenId");
            return (Criteria) this;
        }

        public Criteria andCScreenIdBetween(String value1, String value2) {
            addCriterion("C_SCREEN_ID between", value1, value2, "cScreenId");
            return (Criteria) this;
        }

        public Criteria andCScreenIdNotBetween(String value1, String value2) {
            addCriterion("C_SCREEN_ID not between", value1, value2, "cScreenId");
            return (Criteria) this;
        }

        public Criteria andCMkMcIsNull() {
            addCriterion("C_MK_MC is null");
            return (Criteria) this;
        }

        public Criteria andCMkMcIsNotNull() {
            addCriterion("C_MK_MC is not null");
            return (Criteria) this;
        }

        public Criteria andCMkMcEqualTo(String value) {
            addCriterion("C_MK_MC =", value, "cMkMc");
            return (Criteria) this;
        }

        public Criteria andCMkMcNotEqualTo(String value) {
            addCriterion("C_MK_MC <>", value, "cMkMc");
            return (Criteria) this;
        }

        public Criteria andCMkMcGreaterThan(String value) {
            addCriterion("C_MK_MC >", value, "cMkMc");
            return (Criteria) this;
        }

        public Criteria andCMkMcGreaterThanOrEqualTo(String value) {
            addCriterion("C_MK_MC >=", value, "cMkMc");
            return (Criteria) this;
        }

        public Criteria andCMkMcLessThan(String value) {
            addCriterion("C_MK_MC <", value, "cMkMc");
            return (Criteria) this;
        }

        public Criteria andCMkMcLessThanOrEqualTo(String value) {
            addCriterion("C_MK_MC <=", value, "cMkMc");
            return (Criteria) this;
        }

        public Criteria andCMkMcLike(String value) {
            addCriterion("C_MK_MC like", value, "cMkMc");
            return (Criteria) this;
        }

        public Criteria andCMkMcNotLike(String value) {
            addCriterion("C_MK_MC not like", value, "cMkMc");
            return (Criteria) this;
        }

        public Criteria andCMkMcIn(List<String> values) {
            addCriterion("C_MK_MC in", values, "cMkMc");
            return (Criteria) this;
        }

        public Criteria andCMkMcNotIn(List<String> values) {
            addCriterion("C_MK_MC not in", values, "cMkMc");
            return (Criteria) this;
        }

        public Criteria andCMkMcBetween(String value1, String value2) {
            addCriterion("C_MK_MC between", value1, value2, "cMkMc");
            return (Criteria) this;
        }

        public Criteria andCMkMcNotBetween(String value1, String value2) {
            addCriterion("C_MK_MC not between", value1, value2, "cMkMc");
            return (Criteria) this;
        }

        public Criteria andCCategoryMcIsNull() {
            addCriterion("C_CATEGORY_MC is null");
            return (Criteria) this;
        }

        public Criteria andCCategoryMcIsNotNull() {
            addCriterion("C_CATEGORY_MC is not null");
            return (Criteria) this;
        }

        public Criteria andCCategoryMcEqualTo(String value) {
            addCriterion("C_CATEGORY_MC =", value, "cCategoryMc");
            return (Criteria) this;
        }

        public Criteria andCCategoryMcNotEqualTo(String value) {
            addCriterion("C_CATEGORY_MC <>", value, "cCategoryMc");
            return (Criteria) this;
        }

        public Criteria andCCategoryMcGreaterThan(String value) {
            addCriterion("C_CATEGORY_MC >", value, "cCategoryMc");
            return (Criteria) this;
        }

        public Criteria andCCategoryMcGreaterThanOrEqualTo(String value) {
            addCriterion("C_CATEGORY_MC >=", value, "cCategoryMc");
            return (Criteria) this;
        }

        public Criteria andCCategoryMcLessThan(String value) {
            addCriterion("C_CATEGORY_MC <", value, "cCategoryMc");
            return (Criteria) this;
        }

        public Criteria andCCategoryMcLessThanOrEqualTo(String value) {
            addCriterion("C_CATEGORY_MC <=", value, "cCategoryMc");
            return (Criteria) this;
        }

        public Criteria andCCategoryMcLike(String value) {
            addCriterion("C_CATEGORY_MC like", value, "cCategoryMc");
            return (Criteria) this;
        }

        public Criteria andCCategoryMcNotLike(String value) {
            addCriterion("C_CATEGORY_MC not like", value, "cCategoryMc");
            return (Criteria) this;
        }

        public Criteria andCCategoryMcIn(List<String> values) {
            addCriterion("C_CATEGORY_MC in", values, "cCategoryMc");
            return (Criteria) this;
        }

        public Criteria andCCategoryMcNotIn(List<String> values) {
            addCriterion("C_CATEGORY_MC not in", values, "cCategoryMc");
            return (Criteria) this;
        }

        public Criteria andCCategoryMcBetween(String value1, String value2) {
            addCriterion("C_CATEGORY_MC between", value1, value2, "cCategoryMc");
            return (Criteria) this;
        }

        public Criteria andCCategoryMcNotBetween(String value1, String value2) {
            addCriterion("C_CATEGORY_MC not between", value1, value2, "cCategoryMc");
            return (Criteria) this;
        }

        public Criteria andCCategoryEjflIsNull() {
            addCriterion("C_CATEGORY_EJFL is null");
            return (Criteria) this;
        }

        public Criteria andCCategoryEjflIsNotNull() {
            addCriterion("C_CATEGORY_EJFL is not null");
            return (Criteria) this;
        }

        public Criteria andCCategoryEjflEqualTo(String value) {
            addCriterion("C_CATEGORY_EJFL =", value, "cCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andCCategoryEjflNotEqualTo(String value) {
            addCriterion("C_CATEGORY_EJFL <>", value, "cCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andCCategoryEjflGreaterThan(String value) {
            addCriterion("C_CATEGORY_EJFL >", value, "cCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andCCategoryEjflGreaterThanOrEqualTo(String value) {
            addCriterion("C_CATEGORY_EJFL >=", value, "cCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andCCategoryEjflLessThan(String value) {
            addCriterion("C_CATEGORY_EJFL <", value, "cCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andCCategoryEjflLessThanOrEqualTo(String value) {
            addCriterion("C_CATEGORY_EJFL <=", value, "cCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andCCategoryEjflLike(String value) {
            addCriterion("C_CATEGORY_EJFL like", value, "cCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andCCategoryEjflNotLike(String value) {
            addCriterion("C_CATEGORY_EJFL not like", value, "cCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andCCategoryEjflIn(List<String> values) {
            addCriterion("C_CATEGORY_EJFL in", values, "cCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andCCategoryEjflNotIn(List<String> values) {
            addCriterion("C_CATEGORY_EJFL not in", values, "cCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andCCategoryEjflBetween(String value1, String value2) {
            addCriterion("C_CATEGORY_EJFL between", value1, value2, "cCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andCCategoryEjflNotBetween(String value1, String value2) {
            addCriterion("C_CATEGORY_EJFL not between", value1, value2, "cCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andCCategoryXlIsNull() {
            addCriterion("C_CATEGORY_XL is null");
            return (Criteria) this;
        }

        public Criteria andCCategoryXlIsNotNull() {
            addCriterion("C_CATEGORY_XL is not null");
            return (Criteria) this;
        }

        public Criteria andCCategoryXlEqualTo(String value) {
            addCriterion("C_CATEGORY_XL =", value, "cCategoryXl");
            return (Criteria) this;
        }

        public Criteria andCCategoryXlNotEqualTo(String value) {
            addCriterion("C_CATEGORY_XL <>", value, "cCategoryXl");
            return (Criteria) this;
        }

        public Criteria andCCategoryXlGreaterThan(String value) {
            addCriterion("C_CATEGORY_XL >", value, "cCategoryXl");
            return (Criteria) this;
        }

        public Criteria andCCategoryXlGreaterThanOrEqualTo(String value) {
            addCriterion("C_CATEGORY_XL >=", value, "cCategoryXl");
            return (Criteria) this;
        }

        public Criteria andCCategoryXlLessThan(String value) {
            addCriterion("C_CATEGORY_XL <", value, "cCategoryXl");
            return (Criteria) this;
        }

        public Criteria andCCategoryXlLessThanOrEqualTo(String value) {
            addCriterion("C_CATEGORY_XL <=", value, "cCategoryXl");
            return (Criteria) this;
        }

        public Criteria andCCategoryXlLike(String value) {
            addCriterion("C_CATEGORY_XL like", value, "cCategoryXl");
            return (Criteria) this;
        }

        public Criteria andCCategoryXlNotLike(String value) {
            addCriterion("C_CATEGORY_XL not like", value, "cCategoryXl");
            return (Criteria) this;
        }

        public Criteria andCCategoryXlIn(List<String> values) {
            addCriterion("C_CATEGORY_XL in", values, "cCategoryXl");
            return (Criteria) this;
        }

        public Criteria andCCategoryXlNotIn(List<String> values) {
            addCriterion("C_CATEGORY_XL not in", values, "cCategoryXl");
            return (Criteria) this;
        }

        public Criteria andCCategoryXlBetween(String value1, String value2) {
            addCriterion("C_CATEGORY_XL between", value1, value2, "cCategoryXl");
            return (Criteria) this;
        }

        public Criteria andCCategoryXlNotBetween(String value1, String value2) {
            addCriterion("C_CATEGORY_XL not between", value1, value2, "cCategoryXl");
            return (Criteria) this;
        }

        public Criteria andCSjMcIsNull() {
            addCriterion("C_SJ_MC is null");
            return (Criteria) this;
        }

        public Criteria andCSjMcIsNotNull() {
            addCriterion("C_SJ_MC is not null");
            return (Criteria) this;
        }

        public Criteria andCSjMcEqualTo(String value) {
            addCriterion("C_SJ_MC =", value, "cSjMc");
            return (Criteria) this;
        }

        public Criteria andCSjMcNotEqualTo(String value) {
            addCriterion("C_SJ_MC <>", value, "cSjMc");
            return (Criteria) this;
        }

        public Criteria andCSjMcGreaterThan(String value) {
            addCriterion("C_SJ_MC >", value, "cSjMc");
            return (Criteria) this;
        }

        public Criteria andCSjMcGreaterThanOrEqualTo(String value) {
            addCriterion("C_SJ_MC >=", value, "cSjMc");
            return (Criteria) this;
        }

        public Criteria andCSjMcLessThan(String value) {
            addCriterion("C_SJ_MC <", value, "cSjMc");
            return (Criteria) this;
        }

        public Criteria andCSjMcLessThanOrEqualTo(String value) {
            addCriterion("C_SJ_MC <=", value, "cSjMc");
            return (Criteria) this;
        }

        public Criteria andCSjMcLike(String value) {
            addCriterion("C_SJ_MC like", value, "cSjMc");
            return (Criteria) this;
        }

        public Criteria andCSjMcNotLike(String value) {
            addCriterion("C_SJ_MC not like", value, "cSjMc");
            return (Criteria) this;
        }

        public Criteria andCSjMcIn(List<String> values) {
            addCriterion("C_SJ_MC in", values, "cSjMc");
            return (Criteria) this;
        }

        public Criteria andCSjMcNotIn(List<String> values) {
            addCriterion("C_SJ_MC not in", values, "cSjMc");
            return (Criteria) this;
        }

        public Criteria andCSjMcBetween(String value1, String value2) {
            addCriterion("C_SJ_MC between", value1, value2, "cSjMc");
            return (Criteria) this;
        }

        public Criteria andCSjMcNotBetween(String value1, String value2) {
            addCriterion("C_SJ_MC not between", value1, value2, "cSjMc");
            return (Criteria) this;
        }

        public Criteria andCSjSlIsNull() {
            addCriterion("C_SJ_SL is null");
            return (Criteria) this;
        }

        public Criteria andCSjSlIsNotNull() {
            addCriterion("C_SJ_SL is not null");
            return (Criteria) this;
        }

        public Criteria andCSjSlEqualTo(String value) {
            addCriterion("C_SJ_SL =", value, "cSjSl");
            return (Criteria) this;
        }

        public Criteria andCSjSlNotEqualTo(String value) {
            addCriterion("C_SJ_SL <>", value, "cSjSl");
            return (Criteria) this;
        }

        public Criteria andCSjSlGreaterThan(String value) {
            addCriterion("C_SJ_SL >", value, "cSjSl");
            return (Criteria) this;
        }

        public Criteria andCSjSlGreaterThanOrEqualTo(String value) {
            addCriterion("C_SJ_SL >=", value, "cSjSl");
            return (Criteria) this;
        }

        public Criteria andCSjSlLessThan(String value) {
            addCriterion("C_SJ_SL <", value, "cSjSl");
            return (Criteria) this;
        }

        public Criteria andCSjSlLessThanOrEqualTo(String value) {
            addCriterion("C_SJ_SL <=", value, "cSjSl");
            return (Criteria) this;
        }

        public Criteria andCSjSlLike(String value) {
            addCriterion("C_SJ_SL like", value, "cSjSl");
            return (Criteria) this;
        }

        public Criteria andCSjSlNotLike(String value) {
            addCriterion("C_SJ_SL not like", value, "cSjSl");
            return (Criteria) this;
        }

        public Criteria andCSjSlIn(List<String> values) {
            addCriterion("C_SJ_SL in", values, "cSjSl");
            return (Criteria) this;
        }

        public Criteria andCSjSlNotIn(List<String> values) {
            addCriterion("C_SJ_SL not in", values, "cSjSl");
            return (Criteria) this;
        }

        public Criteria andCSjSlBetween(String value1, String value2) {
            addCriterion("C_SJ_SL between", value1, value2, "cSjSl");
            return (Criteria) this;
        }

        public Criteria andCSjSlNotBetween(String value1, String value2) {
            addCriterion("C_SJ_SL not between", value1, value2, "cSjSl");
            return (Criteria) this;
        }

        public Criteria andCSdSlIsNull() {
            addCriterion("C_SD_SL is null");
            return (Criteria) this;
        }

        public Criteria andCSdSlIsNotNull() {
            addCriterion("C_SD_SL is not null");
            return (Criteria) this;
        }

        public Criteria andCSdSlEqualTo(String value) {
            addCriterion("C_SD_SL =", value, "cSdSl");
            return (Criteria) this;
        }

        public Criteria andCSdSlNotEqualTo(String value) {
            addCriterion("C_SD_SL <>", value, "cSdSl");
            return (Criteria) this;
        }

        public Criteria andCSdSlGreaterThan(String value) {
            addCriterion("C_SD_SL >", value, "cSdSl");
            return (Criteria) this;
        }

        public Criteria andCSdSlGreaterThanOrEqualTo(String value) {
            addCriterion("C_SD_SL >=", value, "cSdSl");
            return (Criteria) this;
        }

        public Criteria andCSdSlLessThan(String value) {
            addCriterion("C_SD_SL <", value, "cSdSl");
            return (Criteria) this;
        }

        public Criteria andCSdSlLessThanOrEqualTo(String value) {
            addCriterion("C_SD_SL <=", value, "cSdSl");
            return (Criteria) this;
        }

        public Criteria andCSdSlLike(String value) {
            addCriterion("C_SD_SL like", value, "cSdSl");
            return (Criteria) this;
        }

        public Criteria andCSdSlNotLike(String value) {
            addCriterion("C_SD_SL not like", value, "cSdSl");
            return (Criteria) this;
        }

        public Criteria andCSdSlIn(List<String> values) {
            addCriterion("C_SD_SL in", values, "cSdSl");
            return (Criteria) this;
        }

        public Criteria andCSdSlNotIn(List<String> values) {
            addCriterion("C_SD_SL not in", values, "cSdSl");
            return (Criteria) this;
        }

        public Criteria andCSdSlBetween(String value1, String value2) {
            addCriterion("C_SD_SL between", value1, value2, "cSdSl");
            return (Criteria) this;
        }

        public Criteria andCSdSlNotBetween(String value1, String value2) {
            addCriterion("C_SD_SL not between", value1, value2, "cSdSl");
            return (Criteria) this;
        }

        public Criteria andCXsWsIsNull() {
            addCriterion("C_XS_WS is null");
            return (Criteria) this;
        }

        public Criteria andCXsWsIsNotNull() {
            addCriterion("C_XS_WS is not null");
            return (Criteria) this;
        }

        public Criteria andCXsWsEqualTo(String value) {
            addCriterion("C_XS_WS =", value, "cXsWs");
            return (Criteria) this;
        }

        public Criteria andCXsWsNotEqualTo(String value) {
            addCriterion("C_XS_WS <>", value, "cXsWs");
            return (Criteria) this;
        }

        public Criteria andCXsWsGreaterThan(String value) {
            addCriterion("C_XS_WS >", value, "cXsWs");
            return (Criteria) this;
        }

        public Criteria andCXsWsGreaterThanOrEqualTo(String value) {
            addCriterion("C_XS_WS >=", value, "cXsWs");
            return (Criteria) this;
        }

        public Criteria andCXsWsLessThan(String value) {
            addCriterion("C_XS_WS <", value, "cXsWs");
            return (Criteria) this;
        }

        public Criteria andCXsWsLessThanOrEqualTo(String value) {
            addCriterion("C_XS_WS <=", value, "cXsWs");
            return (Criteria) this;
        }

        public Criteria andCXsWsLike(String value) {
            addCriterion("C_XS_WS like", value, "cXsWs");
            return (Criteria) this;
        }

        public Criteria andCXsWsNotLike(String value) {
            addCriterion("C_XS_WS not like", value, "cXsWs");
            return (Criteria) this;
        }

        public Criteria andCXsWsIn(List<String> values) {
            addCriterion("C_XS_WS in", values, "cXsWs");
            return (Criteria) this;
        }

        public Criteria andCXsWsNotIn(List<String> values) {
            addCriterion("C_XS_WS not in", values, "cXsWs");
            return (Criteria) this;
        }

        public Criteria andCXsWsBetween(String value1, String value2) {
            addCriterion("C_XS_WS between", value1, value2, "cXsWs");
            return (Criteria) this;
        }

        public Criteria andCXsWsNotBetween(String value1, String value2) {
            addCriterion("C_XS_WS not between", value1, value2, "cXsWs");
            return (Criteria) this;
        }

        public Criteria andCSjDwIsNull() {
            addCriterion("C_SJ_DW is null");
            return (Criteria) this;
        }

        public Criteria andCSjDwIsNotNull() {
            addCriterion("C_SJ_DW is not null");
            return (Criteria) this;
        }

        public Criteria andCSjDwEqualTo(String value) {
            addCriterion("C_SJ_DW =", value, "cSjDw");
            return (Criteria) this;
        }

        public Criteria andCSjDwNotEqualTo(String value) {
            addCriterion("C_SJ_DW <>", value, "cSjDw");
            return (Criteria) this;
        }

        public Criteria andCSjDwGreaterThan(String value) {
            addCriterion("C_SJ_DW >", value, "cSjDw");
            return (Criteria) this;
        }

        public Criteria andCSjDwGreaterThanOrEqualTo(String value) {
            addCriterion("C_SJ_DW >=", value, "cSjDw");
            return (Criteria) this;
        }

        public Criteria andCSjDwLessThan(String value) {
            addCriterion("C_SJ_DW <", value, "cSjDw");
            return (Criteria) this;
        }

        public Criteria andCSjDwLessThanOrEqualTo(String value) {
            addCriterion("C_SJ_DW <=", value, "cSjDw");
            return (Criteria) this;
        }

        public Criteria andCSjDwLike(String value) {
            addCriterion("C_SJ_DW like", value, "cSjDw");
            return (Criteria) this;
        }

        public Criteria andCSjDwNotLike(String value) {
            addCriterion("C_SJ_DW not like", value, "cSjDw");
            return (Criteria) this;
        }

        public Criteria andCSjDwIn(List<String> values) {
            addCriterion("C_SJ_DW in", values, "cSjDw");
            return (Criteria) this;
        }

        public Criteria andCSjDwNotIn(List<String> values) {
            addCriterion("C_SJ_DW not in", values, "cSjDw");
            return (Criteria) this;
        }

        public Criteria andCSjDwBetween(String value1, String value2) {
            addCriterion("C_SJ_DW between", value1, value2, "cSjDw");
            return (Criteria) this;
        }

        public Criteria andCSjDwNotBetween(String value1, String value2) {
            addCriterion("C_SJ_DW not between", value1, value2, "cSjDw");
            return (Criteria) this;
        }

        public Criteria andCBzIsNull() {
            addCriterion("C_BZ is null");
            return (Criteria) this;
        }

        public Criteria andCBzIsNotNull() {
            addCriterion("C_BZ is not null");
            return (Criteria) this;
        }

        public Criteria andCBzEqualTo(String value) {
            addCriterion("C_BZ =", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzNotEqualTo(String value) {
            addCriterion("C_BZ <>", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzGreaterThan(String value) {
            addCriterion("C_BZ >", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzGreaterThanOrEqualTo(String value) {
            addCriterion("C_BZ >=", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzLessThan(String value) {
            addCriterion("C_BZ <", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzLessThanOrEqualTo(String value) {
            addCriterion("C_BZ <=", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzLike(String value) {
            addCriterion("C_BZ like", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzNotLike(String value) {
            addCriterion("C_BZ not like", value, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzIn(List<String> values) {
            addCriterion("C_BZ in", values, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzNotIn(List<String> values) {
            addCriterion("C_BZ not in", values, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzBetween(String value1, String value2) {
            addCriterion("C_BZ between", value1, value2, "cBz");
            return (Criteria) this;
        }

        public Criteria andCBzNotBetween(String value1, String value2) {
            addCriterion("C_BZ not between", value1, value2, "cBz");
            return (Criteria) this;
        }

        public Criteria andCCreatedIsNull() {
            addCriterion("C_CREATED is null");
            return (Criteria) this;
        }

        public Criteria andCCreatedIsNotNull() {
            addCriterion("C_CREATED is not null");
            return (Criteria) this;
        }

        public Criteria andCCreatedEqualTo(Date value) {
            addCriterion("C_CREATED =", value, "cCreated");
            return (Criteria) this;
        }

        public Criteria andCCreatedNotEqualTo(Date value) {
            addCriterion("C_CREATED <>", value, "cCreated");
            return (Criteria) this;
        }

        public Criteria andCCreatedGreaterThan(Date value) {
            addCriterion("C_CREATED >", value, "cCreated");
            return (Criteria) this;
        }

        public Criteria andCCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("C_CREATED >=", value, "cCreated");
            return (Criteria) this;
        }

        public Criteria andCCreatedLessThan(Date value) {
            addCriterion("C_CREATED <", value, "cCreated");
            return (Criteria) this;
        }

        public Criteria andCCreatedLessThanOrEqualTo(Date value) {
            addCriterion("C_CREATED <=", value, "cCreated");
            return (Criteria) this;
        }

        public Criteria andCCreatedIn(List<Date> values) {
            addCriterion("C_CREATED in", values, "cCreated");
            return (Criteria) this;
        }

        public Criteria andCCreatedNotIn(List<Date> values) {
            addCriterion("C_CREATED not in", values, "cCreated");
            return (Criteria) this;
        }

        public Criteria andCCreatedBetween(Date value1, Date value2) {
            addCriterion("C_CREATED between", value1, value2, "cCreated");
            return (Criteria) this;
        }

        public Criteria andCCreatedNotBetween(Date value1, Date value2) {
            addCriterion("C_CREATED not between", value1, value2, "cCreated");
            return (Criteria) this;
        }

        public Criteria andCUpdatedIsNull() {
            addCriterion("C_UPDATED is null");
            return (Criteria) this;
        }

        public Criteria andCUpdatedIsNotNull() {
            addCriterion("C_UPDATED is not null");
            return (Criteria) this;
        }

        public Criteria andCUpdatedEqualTo(Date value) {
            addCriterion("C_UPDATED =", value, "cUpdated");
            return (Criteria) this;
        }

        public Criteria andCUpdatedNotEqualTo(Date value) {
            addCriterion("C_UPDATED <>", value, "cUpdated");
            return (Criteria) this;
        }

        public Criteria andCUpdatedGreaterThan(Date value) {
            addCriterion("C_UPDATED >", value, "cUpdated");
            return (Criteria) this;
        }

        public Criteria andCUpdatedGreaterThanOrEqualTo(Date value) {
            addCriterion("C_UPDATED >=", value, "cUpdated");
            return (Criteria) this;
        }

        public Criteria andCUpdatedLessThan(Date value) {
            addCriterion("C_UPDATED <", value, "cUpdated");
            return (Criteria) this;
        }

        public Criteria andCUpdatedLessThanOrEqualTo(Date value) {
            addCriterion("C_UPDATED <=", value, "cUpdated");
            return (Criteria) this;
        }

        public Criteria andCUpdatedIn(List<Date> values) {
            addCriterion("C_UPDATED in", values, "cUpdated");
            return (Criteria) this;
        }

        public Criteria andCUpdatedNotIn(List<Date> values) {
            addCriterion("C_UPDATED not in", values, "cUpdated");
            return (Criteria) this;
        }

        public Criteria andCUpdatedBetween(Date value1, Date value2) {
            addCriterion("C_UPDATED between", value1, value2, "cUpdated");
            return (Criteria) this;
        }

        public Criteria andCUpdatedNotBetween(Date value1, Date value2) {
            addCriterion("C_UPDATED not between", value1, value2, "cUpdated");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_screen_chart
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 24 14:37:14 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_screen_chart
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}