package com.landasoft.xysh.pojo;

import java.util.Date;

public class TScreenHz {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_hz.S_ID
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    private String sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_hz.S_NAME
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    private String sName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_hz.S_CREATED
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    private Date sCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_hz.S_UPDATED
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    private Date sUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_hz.S_FBL_H
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    private String sFblH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_hz.S_FBL_W
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    private String sFblW;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_hz.S_ID
     *
     * @return the value of t_screen_hz.S_ID
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public String getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_hz.S_ID
     *
     * @param sId the value for t_screen_hz.S_ID
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setsId(String sId) {
        this.sId = sId == null ? null : sId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_hz.S_NAME
     *
     * @return the value of t_screen_hz.S_NAME
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_hz.S_NAME
     *
     * @param sName the value for t_screen_hz.S_NAME
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_hz.S_CREATED
     *
     * @return the value of t_screen_hz.S_CREATED
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public Date getsCreated() {
        return sCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_hz.S_CREATED
     *
     * @param sCreated the value for t_screen_hz.S_CREATED
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setsCreated(Date sCreated) {
        this.sCreated = sCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_hz.S_UPDATED
     *
     * @return the value of t_screen_hz.S_UPDATED
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public Date getsUpdated() {
        return sUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_hz.S_UPDATED
     *
     * @param sUpdated the value for t_screen_hz.S_UPDATED
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setsUpdated(Date sUpdated) {
        this.sUpdated = sUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_hz.S_FBL_H
     *
     * @return the value of t_screen_hz.S_FBL_H
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public String getsFblH() {
        return sFblH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_hz.S_FBL_H
     *
     * @param sFblH the value for t_screen_hz.S_FBL_H
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setsFblH(String sFblH) {
        this.sFblH = sFblH == null ? null : sFblH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_hz.S_FBL_W
     *
     * @return the value of t_screen_hz.S_FBL_W
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public String getsFblW() {
        return sFblW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_hz.S_FBL_W
     *
     * @param sFblW the value for t_screen_hz.S_FBL_W
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setsFblW(String sFblW) {
        this.sFblW = sFblW == null ? null : sFblW.trim();
    }
}