package com.landasoft.xysh.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TScreenListExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public TScreenListExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLIdIsNull() {
            addCriterion("L_ID is null");
            return (Criteria) this;
        }

        public Criteria andLIdIsNotNull() {
            addCriterion("L_ID is not null");
            return (Criteria) this;
        }

        public Criteria andLIdEqualTo(String value) {
            addCriterion("L_ID =", value, "lId");
            return (Criteria) this;
        }

        public Criteria andLIdNotEqualTo(String value) {
            addCriterion("L_ID <>", value, "lId");
            return (Criteria) this;
        }

        public Criteria andLIdGreaterThan(String value) {
            addCriterion("L_ID >", value, "lId");
            return (Criteria) this;
        }

        public Criteria andLIdGreaterThanOrEqualTo(String value) {
            addCriterion("L_ID >=", value, "lId");
            return (Criteria) this;
        }

        public Criteria andLIdLessThan(String value) {
            addCriterion("L_ID <", value, "lId");
            return (Criteria) this;
        }

        public Criteria andLIdLessThanOrEqualTo(String value) {
            addCriterion("L_ID <=", value, "lId");
            return (Criteria) this;
        }

        public Criteria andLIdLike(String value) {
            addCriterion("L_ID like", value, "lId");
            return (Criteria) this;
        }

        public Criteria andLIdNotLike(String value) {
            addCriterion("L_ID not like", value, "lId");
            return (Criteria) this;
        }

        public Criteria andLIdIn(List<String> values) {
            addCriterion("L_ID in", values, "lId");
            return (Criteria) this;
        }

        public Criteria andLIdNotIn(List<String> values) {
            addCriterion("L_ID not in", values, "lId");
            return (Criteria) this;
        }

        public Criteria andLIdBetween(String value1, String value2) {
            addCriterion("L_ID between", value1, value2, "lId");
            return (Criteria) this;
        }

        public Criteria andLIdNotBetween(String value1, String value2) {
            addCriterion("L_ID not between", value1, value2, "lId");
            return (Criteria) this;
        }

        public Criteria andLScreenIdIsNull() {
            addCriterion("L_SCREEN_ID is null");
            return (Criteria) this;
        }

        public Criteria andLScreenIdIsNotNull() {
            addCriterion("L_SCREEN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andLScreenIdEqualTo(String value) {
            addCriterion("L_SCREEN_ID =", value, "lScreenId");
            return (Criteria) this;
        }

        public Criteria andLScreenIdNotEqualTo(String value) {
            addCriterion("L_SCREEN_ID <>", value, "lScreenId");
            return (Criteria) this;
        }

        public Criteria andLScreenIdGreaterThan(String value) {
            addCriterion("L_SCREEN_ID >", value, "lScreenId");
            return (Criteria) this;
        }

        public Criteria andLScreenIdGreaterThanOrEqualTo(String value) {
            addCriterion("L_SCREEN_ID >=", value, "lScreenId");
            return (Criteria) this;
        }

        public Criteria andLScreenIdLessThan(String value) {
            addCriterion("L_SCREEN_ID <", value, "lScreenId");
            return (Criteria) this;
        }

        public Criteria andLScreenIdLessThanOrEqualTo(String value) {
            addCriterion("L_SCREEN_ID <=", value, "lScreenId");
            return (Criteria) this;
        }

        public Criteria andLScreenIdLike(String value) {
            addCriterion("L_SCREEN_ID like", value, "lScreenId");
            return (Criteria) this;
        }

        public Criteria andLScreenIdNotLike(String value) {
            addCriterion("L_SCREEN_ID not like", value, "lScreenId");
            return (Criteria) this;
        }

        public Criteria andLScreenIdIn(List<String> values) {
            addCriterion("L_SCREEN_ID in", values, "lScreenId");
            return (Criteria) this;
        }

        public Criteria andLScreenIdNotIn(List<String> values) {
            addCriterion("L_SCREEN_ID not in", values, "lScreenId");
            return (Criteria) this;
        }

        public Criteria andLScreenIdBetween(String value1, String value2) {
            addCriterion("L_SCREEN_ID between", value1, value2, "lScreenId");
            return (Criteria) this;
        }

        public Criteria andLScreenIdNotBetween(String value1, String value2) {
            addCriterion("L_SCREEN_ID not between", value1, value2, "lScreenId");
            return (Criteria) this;
        }

        public Criteria andLMkMcIsNull() {
            addCriterion("L_MK_MC is null");
            return (Criteria) this;
        }

        public Criteria andLMkMcIsNotNull() {
            addCriterion("L_MK_MC is not null");
            return (Criteria) this;
        }

        public Criteria andLMkMcEqualTo(String value) {
            addCriterion("L_MK_MC =", value, "lMkMc");
            return (Criteria) this;
        }

        public Criteria andLMkMcNotEqualTo(String value) {
            addCriterion("L_MK_MC <>", value, "lMkMc");
            return (Criteria) this;
        }

        public Criteria andLMkMcGreaterThan(String value) {
            addCriterion("L_MK_MC >", value, "lMkMc");
            return (Criteria) this;
        }

        public Criteria andLMkMcGreaterThanOrEqualTo(String value) {
            addCriterion("L_MK_MC >=", value, "lMkMc");
            return (Criteria) this;
        }

        public Criteria andLMkMcLessThan(String value) {
            addCriterion("L_MK_MC <", value, "lMkMc");
            return (Criteria) this;
        }

        public Criteria andLMkMcLessThanOrEqualTo(String value) {
            addCriterion("L_MK_MC <=", value, "lMkMc");
            return (Criteria) this;
        }

        public Criteria andLMkMcLike(String value) {
            addCriterion("L_MK_MC like", value, "lMkMc");
            return (Criteria) this;
        }

        public Criteria andLMkMcNotLike(String value) {
            addCriterion("L_MK_MC not like", value, "lMkMc");
            return (Criteria) this;
        }

        public Criteria andLMkMcIn(List<String> values) {
            addCriterion("L_MK_MC in", values, "lMkMc");
            return (Criteria) this;
        }

        public Criteria andLMkMcNotIn(List<String> values) {
            addCriterion("L_MK_MC not in", values, "lMkMc");
            return (Criteria) this;
        }

        public Criteria andLMkMcBetween(String value1, String value2) {
            addCriterion("L_MK_MC between", value1, value2, "lMkMc");
            return (Criteria) this;
        }

        public Criteria andLMkMcNotBetween(String value1, String value2) {
            addCriterion("L_MK_MC not between", value1, value2, "lMkMc");
            return (Criteria) this;
        }

        public Criteria andLCategoryMcIsNull() {
            addCriterion("L_CATEGORY_MC is null");
            return (Criteria) this;
        }

        public Criteria andLCategoryMcIsNotNull() {
            addCriterion("L_CATEGORY_MC is not null");
            return (Criteria) this;
        }

        public Criteria andLCategoryMcEqualTo(String value) {
            addCriterion("L_CATEGORY_MC =", value, "lCategoryMc");
            return (Criteria) this;
        }

        public Criteria andLCategoryMcNotEqualTo(String value) {
            addCriterion("L_CATEGORY_MC <>", value, "lCategoryMc");
            return (Criteria) this;
        }

        public Criteria andLCategoryMcGreaterThan(String value) {
            addCriterion("L_CATEGORY_MC >", value, "lCategoryMc");
            return (Criteria) this;
        }

        public Criteria andLCategoryMcGreaterThanOrEqualTo(String value) {
            addCriterion("L_CATEGORY_MC >=", value, "lCategoryMc");
            return (Criteria) this;
        }

        public Criteria andLCategoryMcLessThan(String value) {
            addCriterion("L_CATEGORY_MC <", value, "lCategoryMc");
            return (Criteria) this;
        }

        public Criteria andLCategoryMcLessThanOrEqualTo(String value) {
            addCriterion("L_CATEGORY_MC <=", value, "lCategoryMc");
            return (Criteria) this;
        }

        public Criteria andLCategoryMcLike(String value) {
            addCriterion("L_CATEGORY_MC like", value, "lCategoryMc");
            return (Criteria) this;
        }

        public Criteria andLCategoryMcNotLike(String value) {
            addCriterion("L_CATEGORY_MC not like", value, "lCategoryMc");
            return (Criteria) this;
        }

        public Criteria andLCategoryMcIn(List<String> values) {
            addCriterion("L_CATEGORY_MC in", values, "lCategoryMc");
            return (Criteria) this;
        }

        public Criteria andLCategoryMcNotIn(List<String> values) {
            addCriterion("L_CATEGORY_MC not in", values, "lCategoryMc");
            return (Criteria) this;
        }

        public Criteria andLCategoryMcBetween(String value1, String value2) {
            addCriterion("L_CATEGORY_MC between", value1, value2, "lCategoryMc");
            return (Criteria) this;
        }

        public Criteria andLCategoryMcNotBetween(String value1, String value2) {
            addCriterion("L_CATEGORY_MC not between", value1, value2, "lCategoryMc");
            return (Criteria) this;
        }

        public Criteria andLCategoryEjflIsNull() {
            addCriterion("L_CATEGORY_EJFL is null");
            return (Criteria) this;
        }

        public Criteria andLCategoryEjflIsNotNull() {
            addCriterion("L_CATEGORY_EJFL is not null");
            return (Criteria) this;
        }

        public Criteria andLCategoryEjflEqualTo(String value) {
            addCriterion("L_CATEGORY_EJFL =", value, "lCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andLCategoryEjflNotEqualTo(String value) {
            addCriterion("L_CATEGORY_EJFL <>", value, "lCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andLCategoryEjflGreaterThan(String value) {
            addCriterion("L_CATEGORY_EJFL >", value, "lCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andLCategoryEjflGreaterThanOrEqualTo(String value) {
            addCriterion("L_CATEGORY_EJFL >=", value, "lCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andLCategoryEjflLessThan(String value) {
            addCriterion("L_CATEGORY_EJFL <", value, "lCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andLCategoryEjflLessThanOrEqualTo(String value) {
            addCriterion("L_CATEGORY_EJFL <=", value, "lCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andLCategoryEjflLike(String value) {
            addCriterion("L_CATEGORY_EJFL like", value, "lCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andLCategoryEjflNotLike(String value) {
            addCriterion("L_CATEGORY_EJFL not like", value, "lCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andLCategoryEjflIn(List<String> values) {
            addCriterion("L_CATEGORY_EJFL in", values, "lCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andLCategoryEjflNotIn(List<String> values) {
            addCriterion("L_CATEGORY_EJFL not in", values, "lCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andLCategoryEjflBetween(String value1, String value2) {
            addCriterion("L_CATEGORY_EJFL between", value1, value2, "lCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andLCategoryEjflNotBetween(String value1, String value2) {
            addCriterion("L_CATEGORY_EJFL not between", value1, value2, "lCategoryEjfl");
            return (Criteria) this;
        }

        public Criteria andLCategoryXlIsNull() {
            addCriterion("L_CATEGORY_XL is null");
            return (Criteria) this;
        }

        public Criteria andLCategoryXlIsNotNull() {
            addCriterion("L_CATEGORY_XL is not null");
            return (Criteria) this;
        }

        public Criteria andLCategoryXlEqualTo(String value) {
            addCriterion("L_CATEGORY_XL =", value, "lCategoryXl");
            return (Criteria) this;
        }

        public Criteria andLCategoryXlNotEqualTo(String value) {
            addCriterion("L_CATEGORY_XL <>", value, "lCategoryXl");
            return (Criteria) this;
        }

        public Criteria andLCategoryXlGreaterThan(String value) {
            addCriterion("L_CATEGORY_XL >", value, "lCategoryXl");
            return (Criteria) this;
        }

        public Criteria andLCategoryXlGreaterThanOrEqualTo(String value) {
            addCriterion("L_CATEGORY_XL >=", value, "lCategoryXl");
            return (Criteria) this;
        }

        public Criteria andLCategoryXlLessThan(String value) {
            addCriterion("L_CATEGORY_XL <", value, "lCategoryXl");
            return (Criteria) this;
        }

        public Criteria andLCategoryXlLessThanOrEqualTo(String value) {
            addCriterion("L_CATEGORY_XL <=", value, "lCategoryXl");
            return (Criteria) this;
        }

        public Criteria andLCategoryXlLike(String value) {
            addCriterion("L_CATEGORY_XL like", value, "lCategoryXl");
            return (Criteria) this;
        }

        public Criteria andLCategoryXlNotLike(String value) {
            addCriterion("L_CATEGORY_XL not like", value, "lCategoryXl");
            return (Criteria) this;
        }

        public Criteria andLCategoryXlIn(List<String> values) {
            addCriterion("L_CATEGORY_XL in", values, "lCategoryXl");
            return (Criteria) this;
        }

        public Criteria andLCategoryXlNotIn(List<String> values) {
            addCriterion("L_CATEGORY_XL not in", values, "lCategoryXl");
            return (Criteria) this;
        }

        public Criteria andLCategoryXlBetween(String value1, String value2) {
            addCriterion("L_CATEGORY_XL between", value1, value2, "lCategoryXl");
            return (Criteria) this;
        }

        public Criteria andLCategoryXlNotBetween(String value1, String value2) {
            addCriterion("L_CATEGORY_XL not between", value1, value2, "lCategoryXl");
            return (Criteria) this;
        }

        public Criteria andLBzIsNull() {
            addCriterion("L_BZ is null");
            return (Criteria) this;
        }

        public Criteria andLBzIsNotNull() {
            addCriterion("L_BZ is not null");
            return (Criteria) this;
        }

        public Criteria andLBzEqualTo(String value) {
            addCriterion("L_BZ =", value, "lBz");
            return (Criteria) this;
        }

        public Criteria andLBzNotEqualTo(String value) {
            addCriterion("L_BZ <>", value, "lBz");
            return (Criteria) this;
        }

        public Criteria andLBzGreaterThan(String value) {
            addCriterion("L_BZ >", value, "lBz");
            return (Criteria) this;
        }

        public Criteria andLBzGreaterThanOrEqualTo(String value) {
            addCriterion("L_BZ >=", value, "lBz");
            return (Criteria) this;
        }

        public Criteria andLBzLessThan(String value) {
            addCriterion("L_BZ <", value, "lBz");
            return (Criteria) this;
        }

        public Criteria andLBzLessThanOrEqualTo(String value) {
            addCriterion("L_BZ <=", value, "lBz");
            return (Criteria) this;
        }

        public Criteria andLBzLike(String value) {
            addCriterion("L_BZ like", value, "lBz");
            return (Criteria) this;
        }

        public Criteria andLBzNotLike(String value) {
            addCriterion("L_BZ not like", value, "lBz");
            return (Criteria) this;
        }

        public Criteria andLBzIn(List<String> values) {
            addCriterion("L_BZ in", values, "lBz");
            return (Criteria) this;
        }

        public Criteria andLBzNotIn(List<String> values) {
            addCriterion("L_BZ not in", values, "lBz");
            return (Criteria) this;
        }

        public Criteria andLBzBetween(String value1, String value2) {
            addCriterion("L_BZ between", value1, value2, "lBz");
            return (Criteria) this;
        }

        public Criteria andLBzNotBetween(String value1, String value2) {
            addCriterion("L_BZ not between", value1, value2, "lBz");
            return (Criteria) this;
        }

        public Criteria andLKz1IsNull() {
            addCriterion("L_KZ_1 is null");
            return (Criteria) this;
        }

        public Criteria andLKz1IsNotNull() {
            addCriterion("L_KZ_1 is not null");
            return (Criteria) this;
        }

        public Criteria andLKz1EqualTo(String value) {
            addCriterion("L_KZ_1 =", value, "lKz1");
            return (Criteria) this;
        }

        public Criteria andLKz1NotEqualTo(String value) {
            addCriterion("L_KZ_1 <>", value, "lKz1");
            return (Criteria) this;
        }

        public Criteria andLKz1GreaterThan(String value) {
            addCriterion("L_KZ_1 >", value, "lKz1");
            return (Criteria) this;
        }

        public Criteria andLKz1GreaterThanOrEqualTo(String value) {
            addCriterion("L_KZ_1 >=", value, "lKz1");
            return (Criteria) this;
        }

        public Criteria andLKz1LessThan(String value) {
            addCriterion("L_KZ_1 <", value, "lKz1");
            return (Criteria) this;
        }

        public Criteria andLKz1LessThanOrEqualTo(String value) {
            addCriterion("L_KZ_1 <=", value, "lKz1");
            return (Criteria) this;
        }

        public Criteria andLKz1Like(String value) {
            addCriterion("L_KZ_1 like", value, "lKz1");
            return (Criteria) this;
        }

        public Criteria andLKz1NotLike(String value) {
            addCriterion("L_KZ_1 not like", value, "lKz1");
            return (Criteria) this;
        }

        public Criteria andLKz1In(List<String> values) {
            addCriterion("L_KZ_1 in", values, "lKz1");
            return (Criteria) this;
        }

        public Criteria andLKz1NotIn(List<String> values) {
            addCriterion("L_KZ_1 not in", values, "lKz1");
            return (Criteria) this;
        }

        public Criteria andLKz1Between(String value1, String value2) {
            addCriterion("L_KZ_1 between", value1, value2, "lKz1");
            return (Criteria) this;
        }

        public Criteria andLKz1NotBetween(String value1, String value2) {
            addCriterion("L_KZ_1 not between", value1, value2, "lKz1");
            return (Criteria) this;
        }

        public Criteria andLKz2IsNull() {
            addCriterion("L_KZ_2 is null");
            return (Criteria) this;
        }

        public Criteria andLKz2IsNotNull() {
            addCriterion("L_KZ_2 is not null");
            return (Criteria) this;
        }

        public Criteria andLKz2EqualTo(String value) {
            addCriterion("L_KZ_2 =", value, "lKz2");
            return (Criteria) this;
        }

        public Criteria andLKz2NotEqualTo(String value) {
            addCriterion("L_KZ_2 <>", value, "lKz2");
            return (Criteria) this;
        }

        public Criteria andLKz2GreaterThan(String value) {
            addCriterion("L_KZ_2 >", value, "lKz2");
            return (Criteria) this;
        }

        public Criteria andLKz2GreaterThanOrEqualTo(String value) {
            addCriterion("L_KZ_2 >=", value, "lKz2");
            return (Criteria) this;
        }

        public Criteria andLKz2LessThan(String value) {
            addCriterion("L_KZ_2 <", value, "lKz2");
            return (Criteria) this;
        }

        public Criteria andLKz2LessThanOrEqualTo(String value) {
            addCriterion("L_KZ_2 <=", value, "lKz2");
            return (Criteria) this;
        }

        public Criteria andLKz2Like(String value) {
            addCriterion("L_KZ_2 like", value, "lKz2");
            return (Criteria) this;
        }

        public Criteria andLKz2NotLike(String value) {
            addCriterion("L_KZ_2 not like", value, "lKz2");
            return (Criteria) this;
        }

        public Criteria andLKz2In(List<String> values) {
            addCriterion("L_KZ_2 in", values, "lKz2");
            return (Criteria) this;
        }

        public Criteria andLKz2NotIn(List<String> values) {
            addCriterion("L_KZ_2 not in", values, "lKz2");
            return (Criteria) this;
        }

        public Criteria andLKz2Between(String value1, String value2) {
            addCriterion("L_KZ_2 between", value1, value2, "lKz2");
            return (Criteria) this;
        }

        public Criteria andLKz2NotBetween(String value1, String value2) {
            addCriterion("L_KZ_2 not between", value1, value2, "lKz2");
            return (Criteria) this;
        }

        public Criteria andLKz3IsNull() {
            addCriterion("L_KZ_3 is null");
            return (Criteria) this;
        }

        public Criteria andLKz3IsNotNull() {
            addCriterion("L_KZ_3 is not null");
            return (Criteria) this;
        }

        public Criteria andLKz3EqualTo(String value) {
            addCriterion("L_KZ_3 =", value, "lKz3");
            return (Criteria) this;
        }

        public Criteria andLKz3NotEqualTo(String value) {
            addCriterion("L_KZ_3 <>", value, "lKz3");
            return (Criteria) this;
        }

        public Criteria andLKz3GreaterThan(String value) {
            addCriterion("L_KZ_3 >", value, "lKz3");
            return (Criteria) this;
        }

        public Criteria andLKz3GreaterThanOrEqualTo(String value) {
            addCriterion("L_KZ_3 >=", value, "lKz3");
            return (Criteria) this;
        }

        public Criteria andLKz3LessThan(String value) {
            addCriterion("L_KZ_3 <", value, "lKz3");
            return (Criteria) this;
        }

        public Criteria andLKz3LessThanOrEqualTo(String value) {
            addCriterion("L_KZ_3 <=", value, "lKz3");
            return (Criteria) this;
        }

        public Criteria andLKz3Like(String value) {
            addCriterion("L_KZ_3 like", value, "lKz3");
            return (Criteria) this;
        }

        public Criteria andLKz3NotLike(String value) {
            addCriterion("L_KZ_3 not like", value, "lKz3");
            return (Criteria) this;
        }

        public Criteria andLKz3In(List<String> values) {
            addCriterion("L_KZ_3 in", values, "lKz3");
            return (Criteria) this;
        }

        public Criteria andLKz3NotIn(List<String> values) {
            addCriterion("L_KZ_3 not in", values, "lKz3");
            return (Criteria) this;
        }

        public Criteria andLKz3Between(String value1, String value2) {
            addCriterion("L_KZ_3 between", value1, value2, "lKz3");
            return (Criteria) this;
        }

        public Criteria andLKz3NotBetween(String value1, String value2) {
            addCriterion("L_KZ_3 not between", value1, value2, "lKz3");
            return (Criteria) this;
        }

        public Criteria andLKz4IsNull() {
            addCriterion("L_KZ_4 is null");
            return (Criteria) this;
        }

        public Criteria andLKz4IsNotNull() {
            addCriterion("L_KZ_4 is not null");
            return (Criteria) this;
        }

        public Criteria andLKz4EqualTo(String value) {
            addCriterion("L_KZ_4 =", value, "lKz4");
            return (Criteria) this;
        }

        public Criteria andLKz4NotEqualTo(String value) {
            addCriterion("L_KZ_4 <>", value, "lKz4");
            return (Criteria) this;
        }

        public Criteria andLKz4GreaterThan(String value) {
            addCriterion("L_KZ_4 >", value, "lKz4");
            return (Criteria) this;
        }

        public Criteria andLKz4GreaterThanOrEqualTo(String value) {
            addCriterion("L_KZ_4 >=", value, "lKz4");
            return (Criteria) this;
        }

        public Criteria andLKz4LessThan(String value) {
            addCriterion("L_KZ_4 <", value, "lKz4");
            return (Criteria) this;
        }

        public Criteria andLKz4LessThanOrEqualTo(String value) {
            addCriterion("L_KZ_4 <=", value, "lKz4");
            return (Criteria) this;
        }

        public Criteria andLKz4Like(String value) {
            addCriterion("L_KZ_4 like", value, "lKz4");
            return (Criteria) this;
        }

        public Criteria andLKz4NotLike(String value) {
            addCriterion("L_KZ_4 not like", value, "lKz4");
            return (Criteria) this;
        }

        public Criteria andLKz4In(List<String> values) {
            addCriterion("L_KZ_4 in", values, "lKz4");
            return (Criteria) this;
        }

        public Criteria andLKz4NotIn(List<String> values) {
            addCriterion("L_KZ_4 not in", values, "lKz4");
            return (Criteria) this;
        }

        public Criteria andLKz4Between(String value1, String value2) {
            addCriterion("L_KZ_4 between", value1, value2, "lKz4");
            return (Criteria) this;
        }

        public Criteria andLKz4NotBetween(String value1, String value2) {
            addCriterion("L_KZ_4 not between", value1, value2, "lKz4");
            return (Criteria) this;
        }

        public Criteria andLKz5IsNull() {
            addCriterion("L_KZ_5 is null");
            return (Criteria) this;
        }

        public Criteria andLKz5IsNotNull() {
            addCriterion("L_KZ_5 is not null");
            return (Criteria) this;
        }

        public Criteria andLKz5EqualTo(String value) {
            addCriterion("L_KZ_5 =", value, "lKz5");
            return (Criteria) this;
        }

        public Criteria andLKz5NotEqualTo(String value) {
            addCriterion("L_KZ_5 <>", value, "lKz5");
            return (Criteria) this;
        }

        public Criteria andLKz5GreaterThan(String value) {
            addCriterion("L_KZ_5 >", value, "lKz5");
            return (Criteria) this;
        }

        public Criteria andLKz5GreaterThanOrEqualTo(String value) {
            addCriterion("L_KZ_5 >=", value, "lKz5");
            return (Criteria) this;
        }

        public Criteria andLKz5LessThan(String value) {
            addCriterion("L_KZ_5 <", value, "lKz5");
            return (Criteria) this;
        }

        public Criteria andLKz5LessThanOrEqualTo(String value) {
            addCriterion("L_KZ_5 <=", value, "lKz5");
            return (Criteria) this;
        }

        public Criteria andLKz5Like(String value) {
            addCriterion("L_KZ_5 like", value, "lKz5");
            return (Criteria) this;
        }

        public Criteria andLKz5NotLike(String value) {
            addCriterion("L_KZ_5 not like", value, "lKz5");
            return (Criteria) this;
        }

        public Criteria andLKz5In(List<String> values) {
            addCriterion("L_KZ_5 in", values, "lKz5");
            return (Criteria) this;
        }

        public Criteria andLKz5NotIn(List<String> values) {
            addCriterion("L_KZ_5 not in", values, "lKz5");
            return (Criteria) this;
        }

        public Criteria andLKz5Between(String value1, String value2) {
            addCriterion("L_KZ_5 between", value1, value2, "lKz5");
            return (Criteria) this;
        }

        public Criteria andLKz5NotBetween(String value1, String value2) {
            addCriterion("L_KZ_5 not between", value1, value2, "lKz5");
            return (Criteria) this;
        }

        public Criteria andLKz6IsNull() {
            addCriterion("L_KZ_6 is null");
            return (Criteria) this;
        }

        public Criteria andLKz6IsNotNull() {
            addCriterion("L_KZ_6 is not null");
            return (Criteria) this;
        }

        public Criteria andLKz6EqualTo(String value) {
            addCriterion("L_KZ_6 =", value, "lKz6");
            return (Criteria) this;
        }

        public Criteria andLKz6NotEqualTo(String value) {
            addCriterion("L_KZ_6 <>", value, "lKz6");
            return (Criteria) this;
        }

        public Criteria andLKz6GreaterThan(String value) {
            addCriterion("L_KZ_6 >", value, "lKz6");
            return (Criteria) this;
        }

        public Criteria andLKz6GreaterThanOrEqualTo(String value) {
            addCriterion("L_KZ_6 >=", value, "lKz6");
            return (Criteria) this;
        }

        public Criteria andLKz6LessThan(String value) {
            addCriterion("L_KZ_6 <", value, "lKz6");
            return (Criteria) this;
        }

        public Criteria andLKz6LessThanOrEqualTo(String value) {
            addCriterion("L_KZ_6 <=", value, "lKz6");
            return (Criteria) this;
        }

        public Criteria andLKz6Like(String value) {
            addCriterion("L_KZ_6 like", value, "lKz6");
            return (Criteria) this;
        }

        public Criteria andLKz6NotLike(String value) {
            addCriterion("L_KZ_6 not like", value, "lKz6");
            return (Criteria) this;
        }

        public Criteria andLKz6In(List<String> values) {
            addCriterion("L_KZ_6 in", values, "lKz6");
            return (Criteria) this;
        }

        public Criteria andLKz6NotIn(List<String> values) {
            addCriterion("L_KZ_6 not in", values, "lKz6");
            return (Criteria) this;
        }

        public Criteria andLKz6Between(String value1, String value2) {
            addCriterion("L_KZ_6 between", value1, value2, "lKz6");
            return (Criteria) this;
        }

        public Criteria andLKz6NotBetween(String value1, String value2) {
            addCriterion("L_KZ_6 not between", value1, value2, "lKz6");
            return (Criteria) this;
        }

        public Criteria andLCreatedIsNull() {
            addCriterion("L_CREATED is null");
            return (Criteria) this;
        }

        public Criteria andLCreatedIsNotNull() {
            addCriterion("L_CREATED is not null");
            return (Criteria) this;
        }

        public Criteria andLCreatedEqualTo(Date value) {
            addCriterion("L_CREATED =", value, "lCreated");
            return (Criteria) this;
        }

        public Criteria andLCreatedNotEqualTo(Date value) {
            addCriterion("L_CREATED <>", value, "lCreated");
            return (Criteria) this;
        }

        public Criteria andLCreatedGreaterThan(Date value) {
            addCriterion("L_CREATED >", value, "lCreated");
            return (Criteria) this;
        }

        public Criteria andLCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("L_CREATED >=", value, "lCreated");
            return (Criteria) this;
        }

        public Criteria andLCreatedLessThan(Date value) {
            addCriterion("L_CREATED <", value, "lCreated");
            return (Criteria) this;
        }

        public Criteria andLCreatedLessThanOrEqualTo(Date value) {
            addCriterion("L_CREATED <=", value, "lCreated");
            return (Criteria) this;
        }

        public Criteria andLCreatedIn(List<Date> values) {
            addCriterion("L_CREATED in", values, "lCreated");
            return (Criteria) this;
        }

        public Criteria andLCreatedNotIn(List<Date> values) {
            addCriterion("L_CREATED not in", values, "lCreated");
            return (Criteria) this;
        }

        public Criteria andLCreatedBetween(Date value1, Date value2) {
            addCriterion("L_CREATED between", value1, value2, "lCreated");
            return (Criteria) this;
        }

        public Criteria andLCreatedNotBetween(Date value1, Date value2) {
            addCriterion("L_CREATED not between", value1, value2, "lCreated");
            return (Criteria) this;
        }

        public Criteria andLUpdatedIsNull() {
            addCriterion("L_UPDATED is null");
            return (Criteria) this;
        }

        public Criteria andLUpdatedIsNotNull() {
            addCriterion("L_UPDATED is not null");
            return (Criteria) this;
        }

        public Criteria andLUpdatedEqualTo(Date value) {
            addCriterion("L_UPDATED =", value, "lUpdated");
            return (Criteria) this;
        }

        public Criteria andLUpdatedNotEqualTo(Date value) {
            addCriterion("L_UPDATED <>", value, "lUpdated");
            return (Criteria) this;
        }

        public Criteria andLUpdatedGreaterThan(Date value) {
            addCriterion("L_UPDATED >", value, "lUpdated");
            return (Criteria) this;
        }

        public Criteria andLUpdatedGreaterThanOrEqualTo(Date value) {
            addCriterion("L_UPDATED >=", value, "lUpdated");
            return (Criteria) this;
        }

        public Criteria andLUpdatedLessThan(Date value) {
            addCriterion("L_UPDATED <", value, "lUpdated");
            return (Criteria) this;
        }

        public Criteria andLUpdatedLessThanOrEqualTo(Date value) {
            addCriterion("L_UPDATED <=", value, "lUpdated");
            return (Criteria) this;
        }

        public Criteria andLUpdatedIn(List<Date> values) {
            addCriterion("L_UPDATED in", values, "lUpdated");
            return (Criteria) this;
        }

        public Criteria andLUpdatedNotIn(List<Date> values) {
            addCriterion("L_UPDATED not in", values, "lUpdated");
            return (Criteria) this;
        }

        public Criteria andLUpdatedBetween(Date value1, Date value2) {
            addCriterion("L_UPDATED between", value1, value2, "lUpdated");
            return (Criteria) this;
        }

        public Criteria andLUpdatedNotBetween(Date value1, Date value2) {
            addCriterion("L_UPDATED not between", value1, value2, "lUpdated");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_screen_list
     *
     * @mbggenerated do_not_delete_during_merge Sun Apr 26 16:00:37 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_screen_list
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}