package com.landasoft.xysh.pojo;

import java.util.Date;

public class TScreenList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_list.L_ID
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    private String lId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_list.L_SCREEN_ID
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    private String lScreenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_list.L_MK_MC
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    private String lMkMc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_list.L_CATEGORY_MC
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    private String lCategoryMc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_list.L_CATEGORY_EJFL
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    private String lCategoryEjfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_list.L_CATEGORY_XL
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    private String lCategoryXl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_list.L_BZ
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    private String lBz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_list.L_KZ_1
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    private String lKz1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_list.L_KZ_2
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    private String lKz2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_list.L_KZ_3
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    private String lKz3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_list.L_KZ_4
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    private String lKz4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_list.L_KZ_5
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    private String lKz5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_list.L_KZ_6
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    private String lKz6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_list.L_CREATED
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    private Date lCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_list.L_UPDATED
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    private Date lUpdated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_list.L_ID
     *
     * @return the value of t_screen_list.L_ID
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public String getlId() {
        return lId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_list.L_ID
     *
     * @param lId the value for t_screen_list.L_ID
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public void setlId(String lId) {
        this.lId = lId == null ? null : lId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_list.L_SCREEN_ID
     *
     * @return the value of t_screen_list.L_SCREEN_ID
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public String getlScreenId() {
        return lScreenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_list.L_SCREEN_ID
     *
     * @param lScreenId the value for t_screen_list.L_SCREEN_ID
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public void setlScreenId(String lScreenId) {
        this.lScreenId = lScreenId == null ? null : lScreenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_list.L_MK_MC
     *
     * @return the value of t_screen_list.L_MK_MC
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public String getlMkMc() {
        return lMkMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_list.L_MK_MC
     *
     * @param lMkMc the value for t_screen_list.L_MK_MC
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public void setlMkMc(String lMkMc) {
        this.lMkMc = lMkMc == null ? null : lMkMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_list.L_CATEGORY_MC
     *
     * @return the value of t_screen_list.L_CATEGORY_MC
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public String getlCategoryMc() {
        return lCategoryMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_list.L_CATEGORY_MC
     *
     * @param lCategoryMc the value for t_screen_list.L_CATEGORY_MC
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public void setlCategoryMc(String lCategoryMc) {
        this.lCategoryMc = lCategoryMc == null ? null : lCategoryMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_list.L_CATEGORY_EJFL
     *
     * @return the value of t_screen_list.L_CATEGORY_EJFL
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public String getlCategoryEjfl() {
        return lCategoryEjfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_list.L_CATEGORY_EJFL
     *
     * @param lCategoryEjfl the value for t_screen_list.L_CATEGORY_EJFL
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public void setlCategoryEjfl(String lCategoryEjfl) {
        this.lCategoryEjfl = lCategoryEjfl == null ? null : lCategoryEjfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_list.L_CATEGORY_XL
     *
     * @return the value of t_screen_list.L_CATEGORY_XL
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public String getlCategoryXl() {
        return lCategoryXl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_list.L_CATEGORY_XL
     *
     * @param lCategoryXl the value for t_screen_list.L_CATEGORY_XL
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public void setlCategoryXl(String lCategoryXl) {
        this.lCategoryXl = lCategoryXl == null ? null : lCategoryXl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_list.L_BZ
     *
     * @return the value of t_screen_list.L_BZ
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public String getlBz() {
        return lBz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_list.L_BZ
     *
     * @param lBz the value for t_screen_list.L_BZ
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public void setlBz(String lBz) {
        this.lBz = lBz == null ? null : lBz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_list.L_KZ_1
     *
     * @return the value of t_screen_list.L_KZ_1
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public String getlKz1() {
        return lKz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_list.L_KZ_1
     *
     * @param lKz1 the value for t_screen_list.L_KZ_1
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public void setlKz1(String lKz1) {
        this.lKz1 = lKz1 == null ? null : lKz1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_list.L_KZ_2
     *
     * @return the value of t_screen_list.L_KZ_2
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public String getlKz2() {
        return lKz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_list.L_KZ_2
     *
     * @param lKz2 the value for t_screen_list.L_KZ_2
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public void setlKz2(String lKz2) {
        this.lKz2 = lKz2 == null ? null : lKz2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_list.L_KZ_3
     *
     * @return the value of t_screen_list.L_KZ_3
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public String getlKz3() {
        return lKz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_list.L_KZ_3
     *
     * @param lKz3 the value for t_screen_list.L_KZ_3
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public void setlKz3(String lKz3) {
        this.lKz3 = lKz3 == null ? null : lKz3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_list.L_KZ_4
     *
     * @return the value of t_screen_list.L_KZ_4
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public String getlKz4() {
        return lKz4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_list.L_KZ_4
     *
     * @param lKz4 the value for t_screen_list.L_KZ_4
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public void setlKz4(String lKz4) {
        this.lKz4 = lKz4 == null ? null : lKz4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_list.L_KZ_5
     *
     * @return the value of t_screen_list.L_KZ_5
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public String getlKz5() {
        return lKz5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_list.L_KZ_5
     *
     * @param lKz5 the value for t_screen_list.L_KZ_5
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public void setlKz5(String lKz5) {
        this.lKz5 = lKz5 == null ? null : lKz5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_list.L_KZ_6
     *
     * @return the value of t_screen_list.L_KZ_6
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public String getlKz6() {
        return lKz6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_list.L_KZ_6
     *
     * @param lKz6 the value for t_screen_list.L_KZ_6
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public void setlKz6(String lKz6) {
        this.lKz6 = lKz6 == null ? null : lKz6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_list.L_CREATED
     *
     * @return the value of t_screen_list.L_CREATED
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public Date getlCreated() {
        return lCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_list.L_CREATED
     *
     * @param lCreated the value for t_screen_list.L_CREATED
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public void setlCreated(Date lCreated) {
        this.lCreated = lCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_list.L_UPDATED
     *
     * @return the value of t_screen_list.L_UPDATED
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public Date getlUpdated() {
        return lUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_list.L_UPDATED
     *
     * @param lUpdated the value for t_screen_list.L_UPDATED
     *
     * @mbggenerated Sun Apr 26 16:00:37 CST 2020
     */
    public void setlUpdated(Date lUpdated) {
        this.lUpdated = lUpdated;
    }
}