package com.landasoft.xysh.pojo;

import java.util.Date;

public class TScreenChart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_chart.C_ID
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    private String cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_chart.C_SCREEN_ID
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    private String cScreenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_chart.C_MK_MC
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    private String cMkMc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_chart.C_CATEGORY_MC
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    private String cCategoryMc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_chart.C_CATEGORY_EJFL
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    private String cCategoryEjfl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_chart.C_CATEGORY_XL
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    private String cCategoryXl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_chart.C_SJ_MC
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    private String cSjMc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_chart.C_SJ_SL
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    private String cSjSl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_chart.C_SD_SL
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    private String cSdSl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_chart.C_XS_WS
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    private String cXsWs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_chart.C_SJ_DW
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    private String cSjDw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_chart.C_BZ
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    private String cBz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_chart.C_CREATED
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    private Date cCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_screen_chart.C_UPDATED
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    private Date cUpdated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_chart.C_ID
     *
     * @return the value of t_screen_chart.C_ID
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_chart.C_ID
     *
     * @param cId the value for t_screen_chart.C_ID
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_chart.C_SCREEN_ID
     *
     * @return the value of t_screen_chart.C_SCREEN_ID
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public String getcScreenId() {
        return cScreenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_chart.C_SCREEN_ID
     *
     * @param cScreenId the value for t_screen_chart.C_SCREEN_ID
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setcScreenId(String cScreenId) {
        this.cScreenId = cScreenId == null ? null : cScreenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_chart.C_MK_MC
     *
     * @return the value of t_screen_chart.C_MK_MC
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public String getcMkMc() {
        return cMkMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_chart.C_MK_MC
     *
     * @param cMkMc the value for t_screen_chart.C_MK_MC
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setcMkMc(String cMkMc) {
        this.cMkMc = cMkMc == null ? null : cMkMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_chart.C_CATEGORY_MC
     *
     * @return the value of t_screen_chart.C_CATEGORY_MC
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public String getcCategoryMc() {
        return cCategoryMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_chart.C_CATEGORY_MC
     *
     * @param cCategoryMc the value for t_screen_chart.C_CATEGORY_MC
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setcCategoryMc(String cCategoryMc) {
        this.cCategoryMc = cCategoryMc == null ? null : cCategoryMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_chart.C_CATEGORY_EJFL
     *
     * @return the value of t_screen_chart.C_CATEGORY_EJFL
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public String getcCategoryEjfl() {
        return cCategoryEjfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_chart.C_CATEGORY_EJFL
     *
     * @param cCategoryEjfl the value for t_screen_chart.C_CATEGORY_EJFL
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setcCategoryEjfl(String cCategoryEjfl) {
        this.cCategoryEjfl = cCategoryEjfl == null ? null : cCategoryEjfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_chart.C_CATEGORY_XL
     *
     * @return the value of t_screen_chart.C_CATEGORY_XL
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public String getcCategoryXl() {
        return cCategoryXl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_chart.C_CATEGORY_XL
     *
     * @param cCategoryXl the value for t_screen_chart.C_CATEGORY_XL
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setcCategoryXl(String cCategoryXl) {
        this.cCategoryXl = cCategoryXl == null ? null : cCategoryXl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_chart.C_SJ_MC
     *
     * @return the value of t_screen_chart.C_SJ_MC
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public String getcSjMc() {
        return cSjMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_chart.C_SJ_MC
     *
     * @param cSjMc the value for t_screen_chart.C_SJ_MC
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setcSjMc(String cSjMc) {
        this.cSjMc = cSjMc == null ? null : cSjMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_chart.C_SJ_SL
     *
     * @return the value of t_screen_chart.C_SJ_SL
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public String getcSjSl() {
        return cSjSl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_chart.C_SJ_SL
     *
     * @param cSjSl the value for t_screen_chart.C_SJ_SL
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setcSjSl(String cSjSl) {
        this.cSjSl = cSjSl == null ? null : cSjSl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_chart.C_SD_SL
     *
     * @return the value of t_screen_chart.C_SD_SL
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public String getcSdSl() {
        return cSdSl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_chart.C_SD_SL
     *
     * @param cSdSl the value for t_screen_chart.C_SD_SL
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setcSdSl(String cSdSl) {
        this.cSdSl = cSdSl == null ? null : cSdSl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_chart.C_XS_WS
     *
     * @return the value of t_screen_chart.C_XS_WS
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public String getcXsWs() {
        return cXsWs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_chart.C_XS_WS
     *
     * @param cXsWs the value for t_screen_chart.C_XS_WS
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setcXsWs(String cXsWs) {
        this.cXsWs = cXsWs == null ? null : cXsWs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_chart.C_SJ_DW
     *
     * @return the value of t_screen_chart.C_SJ_DW
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public String getcSjDw() {
        return cSjDw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_chart.C_SJ_DW
     *
     * @param cSjDw the value for t_screen_chart.C_SJ_DW
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setcSjDw(String cSjDw) {
        this.cSjDw = cSjDw == null ? null : cSjDw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_chart.C_BZ
     *
     * @return the value of t_screen_chart.C_BZ
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public String getcBz() {
        return cBz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_chart.C_BZ
     *
     * @param cBz the value for t_screen_chart.C_BZ
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setcBz(String cBz) {
        this.cBz = cBz == null ? null : cBz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_chart.C_CREATED
     *
     * @return the value of t_screen_chart.C_CREATED
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public Date getcCreated() {
        return cCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_chart.C_CREATED
     *
     * @param cCreated the value for t_screen_chart.C_CREATED
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setcCreated(Date cCreated) {
        this.cCreated = cCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_screen_chart.C_UPDATED
     *
     * @return the value of t_screen_chart.C_UPDATED
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public Date getcUpdated() {
        return cUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_screen_chart.C_UPDATED
     *
     * @param cUpdated the value for t_screen_chart.C_UPDATED
     *
     * @mbggenerated Fri Apr 24 14:37:14 CST 2020
     */
    public void setcUpdated(Date cUpdated) {
        this.cUpdated = cUpdated;
    }
}